
---
- name: Update Grafana Repository Key
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553
  when: ansible_distribution == 'Ubuntu'

- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Add Elasticsearch GPG Key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  when: ansible_distribution == 'Ubuntu'

- name: Install Elasticsearch
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present
    filename: elasticsearch-7.x
  when: ansible_distribution == 'Ubuntu'

- name: Install Elasticsearch
  yum_repository:
    name: elasticsearch-7.x
    description: Elasticsearch repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: 1
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  when: ansible_distribution == 'CentOS'

- name: Install Elasticsearch
  package:
    name: elasticsearch
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Install Kibana
  apt:
    name: kibana
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install Kibana
  yum:
    name: kibana
    state: present
  when: ansible_distribution == 'CentOS'

- name: Install Logstash
  apt:
    name: logstash
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install Logstash
  yum:
    name: logstash
    state: present
  when: ansible_distribution == 'CentOS'

- name: install nagios (Ubuntu)
  apt:
    name: nagios3
    state: latest
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install Apache
  package:
    name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    state: present


- name: Install MariaDB
   package:
     name: "{{ 'mysql-server' if ansible_os_family == 'Debian' else 'mariadb-server' }}"
     state: present

- name: Install PHP

  package:

    name: "{{ 'php libapache2-mod-php' if ansible_os_family == 'Debian' else 'php' }}"

    state: present


- name: Install PHP Extensions

  package:

    name: "{{ item }}"

    state: present

  loop:

    - "{{ 'php-mysql' if ansible_os_family == 'Debian' else 'php-mysqlnd' }}"

    - "{{ 'php-xml' if ansible_os_family == 'Debian' else 'php-xml' }}"

    - "{{ 'php-mbstring' if ansible_os_family == 'Debian' else 'php-mbstring' }}"

    - "{{ 'php-curl' if ansible_os_family == 'Debian' else 'php-curl' }}"


- name: Start and enable Apache

  service:

    name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"

    state: started

    enabled: yes


- name: Start and enable MySQL/MariaDB

  service:

    name: "{{ 'mysql' if ansible_os_family == 'Debian' else 'mariadb' }}"

    state: started

    enabled: yes
