---

- name: Install Kibana
  apt:
    name: kibana
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install Kibana
  yum:
    name: kibana
    state: present
  when: ansible_distribution == 'CentOS'

- name: Install Logstash
  apt:
    name: logstash
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install Logstash
  yum:
    name: logstash
    state: present
  when: ansible_distribution == 'CentOS'

- name: install nagios (Ubuntu)
  apt:
    name: nagios3
    state: latest
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'
